### ISSUE TITLE
Inviting contributors

### ISSUE THREAD

**Issue by justincy** [justincy/signs-of-the-second-coming#27]
I want to invite and encourage others to contribute. People shouldn't have to know anything about node, DOT, graphiz, or GitHub. That means I need to do a few things:

* [x] Move the contributing doc to the website (while I'm at it, I should add more detail about how to contribute in specific ways) #30
* [x] Make the Feedback link more than just an email link. It should open a form. #29
* [x] Ideally the full list of scriptures and signs would be published on the website so that people can easily see what has already been done (as opposed to just linking to GitHub). #28
